### ISSUE TITLE
Any reason why pantheon-mail is not maintained

### ISSUE THREAD

**Issue by EugenMayer** [alucryd/aur-alucryd#103]
Hello, thanks for your work.

Any chance you could give an idea why pantheon-mail is so oudated? Also the official aur repo is very outdated ( and broken ).
would be great to understand if there is something special about it? 

Thanks

**Comment by alucryd** [comment]
Hey, thanks for the kind words. There hasn't been a release in 2 years, and gnome is breaking with each new iteration so it's no wonder the stable version isn't working anymore. As for the git version, I haven't had time to check it in a while. In any case I disowned the aur packages so that someone with enough time on their hands can take care of it.
